--- 
addons: 
  chrome: stable
cache: 
  directories: 
    - node_modules
language: node_js
node_js: 
  - "13.12.0"
before_install:
  # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "npm config set spin false"
services:
 - xvfb
before_script:
  - "npm install"

script: "npm test"
sudo: required


