--- 
addons: 
  chrome: stable
before_install: 
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm config set spin false"
before_script: 
  - "npm install"
cache: 
  directories: 
    - node_modules
language: node_js
node_js: 
  - "13.12.0"
script: "npm test -- --suite dresssearchresults"
sudo: required
