--- 
addons: 
  chrome: stable
  services: 
    - xvfb
before_install: 
  - "export DISPLAY=:99.0"
  - "npm config set spin false"
cache: 
  directories: 
    - node_modules
language: node_js
node_js: 
  - "13.12.0"
script: "npm test -- --suite alltest"
sudo: required


